# This requires docker-compose 1.6.0 or later
version: '2'
services:
  rtpengine:
    privileged: true
    build:
      context: ./rtpengine-docker/
      dockerfile: Dockerfile
    network_mode: host
    environment:
      # Comment the variables that you don't want to be used for the configuration
      RUN_RTPENGINE: "yes"
      #LISTEN_TCP: 25060
      #LISTEN_UDP: 12222
      LISTEN_NG: 0.0.0.0:8800
      LISTEN_CLI: 127.0.0.1:60001
      # INTERFACES: "internal/12.23.34.45 external/23.34.45.54"
      # INTERFACES: "12.23.34.45!23.34.45.56"
      TIMEOUT: 60
      SILENT_TIMEOUT: 3600
      FORK: "no"
      # TOS: 184
      TABLE: 40
      NO_FALLBACK: "yes"
      PORT_MIN: 10000
      PORT_MAX: 19999
      # REDIS: 127.0.0.1:6379
      # REDIS_DB: 1
      # REDIS_READ: 127.0.0.1:6379
      # REDIS_READ_DB: 1
      # REDIS_WRITE: 127.0.0.1:6379
      # REDIS_WRITE_DB: 1
      # B2B_URL: http://127.0.0.1:8090/
      LOG_LEVEL: 6
      LOG_FACILITY: local0
      # LOG_FACILITY_CDR: daemon
      # LOG_FACILITY_RTCP: daemon
      # NUM_THREADS: 5
      # DELETE_DELAY: 30
      # GRAPHITE: 9006
      # GRAPHITE_INTERVAL: 60
      # GRAPHITE_PREFIX: myownprefix
      # MAX_SESSIONS: 5000
  kamailio:
    privileged: true
    build:
      context: ./kamailio-docker/
      dockerfile: Dockerfile
    network_mode: host
    environment:
      KAM_DEFINE_DB_MOD_FILE: "db_sqlite.so"
      KAM_DEFINE_DBURL: "sqlite:////etc/kamailio/kamailio.sqlite"
      KAM_DEFINE_WITH_UDP: "true"
      KAM_DEFINE_WITH_TCP: "true"
      KAM_DEFINE_WITH_TLS: "true"
      KAM_DEFINE_WITH_WEBSOCKETS: "true"
      KAM_DEFINE_WITH_USRLOCDB: "true"
      KAM_DEFINE_WITH_ANTIFLOOD: "true"
      KAM_DEFINE_WITH_LOADBALANCE: "true"
      KAM_DEFINE_WITH_DEBUG: "false"
      KAM_DEFINE_WITH_STATSD: "false"
      KAM_DEFINE_TLS_CONFIG_PATH: "/etc/kamailio/tls_mod.cfg"
      KAM_INT_IP: "0.0.0.0"
      KAM_EXT_IP: "127.0.0.1"
      KAM_UDP_PORT: "5060"
      KAM_TCP_PORT: "5060"
      KAM_TLS_PORT: "5061"
      KAM_STATSD_PORT: "9125"
      KAM_STATSD_IP: "127.0.0.1"
      KAM_SHM_FORCE_ALLOC: "yes"
      KAM_SHM_MEM_SIZE: "128"
      KAM_TCP_TIMEOUT: "300"
      KAM_HOMER_HEP_VERSION: "3"

