#!/usr/local/bin/docker-compose -f
version: '2'
services:

    db:
        environment:
            MYSQL_ROOT_PASSWORD: soopertopsecret
            MYSQL_USER: kam
            MYSQL_PASSWORD: topsecret
            MYSQL_DATABASE: kamailio
        image: mysql:5.5

    rtpengine:
        privileged: true
        build:
            context: sherlock-rtpengine/
            dockerfile: Dockerfile
        tty: true
        stdin_open: true
        environment:
            # Comment the variables that you don't want to be used for the configuration
            RUN_RTPENGINE: "yes"
            #LISTEN_TCP: 25060
            #LISTEN_UDP: 12222
            LISTEN_NG: 60000
            LISTEN_CLI: 60001
            INTERFACES: "priv/127.0.0.1 pub/127.0.0.1!23.34.45.54"
            # PUBLIC_IPV4: "23.34.45.54"
            # INTERFACES: "12.23.34.45!23.34.45.56"
            # KERNEL: ???
            # FLUSH_IPTABLES: ???
            TIMEOUT: 60
            SILENT_TIMEOUT: 3600
            FORK: "no"
            # TOS: 184
            # TABLE: 40 < -- only in kernel mode
            NO_FALLBACK: "yes"
            PORT_MIN: 10000
            PORT_MAX: 19999
            # REDIS: 127.0.0.1:6379
            # REDIS_DB: 1
            # REDIS_READ: 127.0.0.1:6379
            # REDIS_READ_DB: 1
            # REDIS_WRITE: 127.0.0.1:6379
            # REDIS_WRITE_DB: 1
            # B2B_URL: http://127.0.0.1:8090/
            LOG_LEVEL: 6
            LOG_FACILITY: local1
            # LOG_FACILITY_CDR: daemon
            # LOG_FACILITY_RTCP: daemon
            # NUM_THREADS: 5
            # DELETE_DELAY: 30
            # GRAPHITE: 9006
            # GRAPHITE_INTERVAL: 60
            # GRAPHITE_PREFIX: myownprefix
            # MAX_SESSIONS: 5000
            # PIDFILE: ???
            # RE_GROUP: ???
            # RE_USER: ???
            # RUNTIME: ???
            # UNLOAD_MODULE: ???

    api:
      build:
        context: .
        dockerfile: Dockerfile.importer
      depends_on:
        - db
      ports:
        - 8080:8080
      command: >-
        sh -c "./kam-user-api"
      environment:
        SUBSCRIBER_DB_CONNECTION: >-
          mysql://kam:topsecret@tcp(db:3306)/kamailio

#    kam:
#      build:
#        context: .
#        dockerfile: Dockerfile.alpine-server
#      ports:
#        - 25060
#      tty: true
#      command: >-
#        sh -c '
#        /config.sh &&
#        sleep 8 &&
#        (
#          ( kamdbctl add-tables standard &&
#            yes | kamdbctl reinit ||
#            kamdbctl grant
#          ) || true
#        ) &&
#        sleep 8 &&
#        /kamailio.sh' #wellp
#      depends_on:
#        - db
#      environment:
#        PW: soopertopsecret
#        KAMAILIO_DBACCESSHOST: '%' #yep
#        KAMAILIO_DBENGINE: MYSQL
#        KAMAILIO_DBHOST: db
#        KAMAILIO_DBROOTUSER: root
#        KAMAILIO_DBNAME: kamailio
#        KAMAILIO_DBROPW: topsecret
#        KAMAILIO_DBROUSER: kam
#        KAMAILIO_DBRWPW: topsecret
#        KAMAILIO_DBRWUSER: kam
#        SIP_DOMAIN: 10.1.1.147
#        REGISTRAR_DNS: 10.1.1.147
#        PUBLIC_DNS: 10.1.1.147
#        DNS_ALIAS1: 10.1.1.147
#        DNS_ALIAS2: 10.1.1.147
#        DNS_ALIAS3: 10.1.1.147
#        OPTIONS: "WITH_REGISTRAR WITH_HUB WITH_AUTH WITH_NATSIPPING WITH_USRLOCDB WITH_MYSQL WITH_MULTIDOMAIN WITH_ALIASDB WITH_PRESENCE"

    registrar:
        build: .
        tty: true
        command: >-
            sh -c '
            /config.sh &&
            (/migrate.sh || true) &&
            /kamailio.sh'
        depends_on:
            - db
            - rtpengine
        #network_mode: host
        #dns: 127.0.0.1
        #links:
        #  - rtpengine:rtpengine.mctestyface.com
        #extra_hosts:
        #  - "hub.mctestyface.com:127.0.0.1"
        #expose:
        #  - "25060/tcp"
        ports:
          - "25060:25060/tcp"
        environment:
            PW: soopertopsecret
            KAMAILIO_CFG: /etc/kamailio/sherlock-platform.cfg
            KAMAILIO_DBENGINE: MYSQL
            KAMAILIO_DBHOST: db
            KAMAILIO_DBROOTUSER: root
            KAMAILIO_DBNAME: kamailio
            KAMAILIO_DBROPW: topsecret
            KAMAILIO_DBROUSER: kam
            KAMAILIO_DBRWPW: topsecret
            KAMAILIO_DBRWUSER: kam
            SOURCE_TAG: REGISTRAR
            CD_HOST: localhost
            CD_PORT: 8000
            PUBLIC_IP: 10.1.1.147
            #LISTEN_IP: 0.0.0.0
            LISTEN_SIP: 25060
            LISTEN_TLS: 25061
            DNS_DOMAIN: 10.1.1.147
            PUBLIC_DNS: 10.1.1.147
            DNS_ALIAS1: 10.1.1.147
            DNS_ALIAS2: 10.1.1.147
            DNS_ALIAS3: 10.1.1.147
            SOLVES_ADDR: pbx.jim.visualaccess.net
            SOLVES_PORT: 25070
            SOLVES_BRIDGE: 100010001
            SOLVES_LCR_ID: 1
            # REGISTRAR_DNS: registrar.mctestyface.com
            # HUB_DNS: hub.mctestyface.com
            # REGISTRAR_PORT_SIP: 25060
            # HUB_PORT_SIP: 25080
            # RTPENGINE_HOSTS: udp:127.0.0.1:60000
            RTPENGINE_HOSTS: udp:rtpengine.mctestyface.com:60000
            # OPTIONS: WITH_REGISTRAR WITH_HUB WITH_CALLDIRECTOR WITH_TLS WITH_AUTH WITH_IPAUTH WITH_NAT WITH_NATSIPPING WITH_SIPCAPTURE WITH_USRLOCDB WITH_MYSQL WITH_MULTIDOMAIN WITH_ALIASDB WITH_PRESENCE WITH_EDGE
            OPTIONS: WITH_REGISTRAR WITH_LCR WITH_AUTH WITH_USRLOCDB WITH_MYSQL WITH_MULTIDOMAIN WITH_ALIASDB WITH_PRESENCE
